// <auto-generated />
namespace swishes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddWishes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWishes));
        
        string IMigrationMetadata.Id
        {
            get { return "201305292159318_AddWishes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
